#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-tianying-portal-web
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://10.6.105.185:8080/eureka
server:
  port: 80


redis:
  hostname: 10.6.24.249
  password: wmsrfredis
  port: 6379

xxl-sso:
  excluded:
    paths: 
xxl:
  sso:
    server: http://xxlssoserver.com/xxl-sso-server
    logout:
      path: /logout
    redis:
      address: redis://xxltest-sso:wmsrfredis@10.6.24.249:6379/0
#      address: redis://127.0.0.1:6379


