###服务启动端口号
server:
  port: 8500
###服务名称(服务注册到eureka名称)  
eureka:
  client:
    service-url:
      defaultZone: http://10.6.105.185:8080/eureka



spring:
  application:
    name:  app-tianying-goods
  redis:
    host: 10.6.24.249
    password: wmsrfredis
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: wmstest
    password: wmstest
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.6.86.36:3306/meite_member?useUnicode=true&characterEncoding=UTF-8
  #    url: jdbc:mysql://127.0.0.1:3306/goods?useUnicode=true&characterEncoding=UTF-
  data:
    elasticsearch:
      ####集群名称
      cluster-name: elasticsearch-cluster
      ####地址
      cluster-nodes: 192.168.253.145:9300
  kafka:
    # kafka服务器地址(可以多个)
    bootstrap-servers: 192.168.253.145:9092
  